version: '3'
services:
  aries-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    command: >
      start
      -l Issuer
      -it http 0.0.0.0 8880
      -ot http
      --admin 0.0.0.0 8038
      --admin-insecure-mode
      -e http://host.docker.internal:8880
      --ledger-url http://test.bcovrin.vonx.io
      --wallet-type indy
      --wallet-name issuerwallet
      --wallet-key issuerkey
      --log-level 'info'
      --auto-accept-invites
      --auto-accept-requests
      --auto-ping-connection
      --seed issuer00000000000000000000000000
    ports:
      - "8880:8880"
      - "8031:8031"
    volumes:
      - $PWD:/home/indy/logs
    networks:
      - von_von
networks:
  von_von:
    external: true
