x-trino-volumes:
  &trino-volumes
      - ./trino-config-coordinator:/etc/trino
      - ./trino-config-coordinator/catalog:/etc/trino/catalog

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db_mysql/init_mysql:/docker-entrypoint-initdb.d
      - ./db_mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 'password'  
  trino_coordinator:
    image: trinodb/trino
    container_name: trino-coordinator
    ports: 
      - "8080:8080"
    volumes: *trino-volumes
  
  trino_worker-1: 
    image: trinodb/trino
    container_name: trino-worker-1
    ports: 
      - "8081:8080"
    volumes: 
      - ./trino-config-worker-1:/etc/trino
      - ./trino-config-worker-1/catalog:/etc/trino/catalog
  mysql-worker-1:
    image: mysql:8.1
    container_name: mysql-worker-1
    ports:
      - "3307:3306"
    volumes:
      - ./db_mysql/init_mysql_worker-1:/docker-entrypoint-initdb.d
      - ./db_mysql/mysqld_worker-1.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 'password' 
  
  trino_worker-2: 
    image: trinodb/trino
    container_name: trino-worker-2
    ports: 
      - "8082:8080"
    volumes: 
      - ./trino-config-worker-2:/etc/trino
      - ./trino-config-worker-2/catalog:/etc/trino/catalog
  mysql-worker-2:
    image: mysql:8.1
    container_name: mysql-worker-2
    ports:
      - "3308:3306"
    volumes:
      - ./db_mysql/init_mysql_worker-2:/docker-entrypoint-initdb.d
      - ./db_mysql/mysqld_worker-2.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 'password' 