x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

version: "3.7"
services:
  redis:
    image: redis:7
    container_name: superset_cache
    #restart: unless-stopped
    volumes:
      - redis:/data

  db:
    env_file: superset/.env
    image: postgres:15
    container_name: superset_db
    #restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./superset/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  superset:
    env_file: superset/.env
    build:
        context: ./superset
        dockerfile: dockerfile
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - '8088:8088'

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false


