services:

    # Controllers
    dao-controller:
        build:
            context: ../dao-controller/
            args:
                - RUNMODE=${RUNMODE}
                - DAO_AGENT_HOST=${DAO_AGENT_HOST}
        ports:
            - 9031:80
        networks:
            - aca

networks:
    aca: